---
- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:

  - name: Create a resource group
    azure_rm_resourcegroup:
      name: ansible-rg01
      location: centralindia

  - name: Create storage account
    azure_rm_storageaccount:
      resource_group: ansible-rg01
      name: ikclassessa587
      account_type: Standard_LRS

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: ansible-rg01
      name: testvn001
      address_prefixes: "10.10.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: ansible-rg01
      name: subnet001
      address_prefix: "10.10.0.0/24"
      virtual_network: testvn001

  - name: Create public ip
    azure_rm_publicipaddress:
      resource_group: ansible-rg01
      allocation_method: Static
      name: publicip001

  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: ansible-rg01
      name: secgroup001
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound

  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: ansible-rg01
      name: testnic001
      virtual_network: testvn001
      subnet: subnet001
      public_ip_name: publicip001
      security_group: secgroup001

  - name: Create virtual machine
    azure_rm_virtualmachine:
      resource_group: ansible-rg01
      name: testvm001
      vm_size: Standard_B2s
      admin_username: azureuser
      admin_password: P@55w.rd1234
      network_interfaces: testnic001
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest